name: "CI"

on: [workflow_dispatch, pull_request]

jobs:
  phpcs_psr12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install PHP_CodeSniffer
        run: sudo apt-get -y install php-codesniffer
      - name: Set phpcs to ignore warnings in return value
        run: sudo phpcs --config-set ignore_warnings_on_exit 1
      - name: Run phpcs
        run: phpcs --standard=PSR12 html
